### ISSUE TITLE
Tests fail with gcc-12

### ISSUE THREAD

**Issue by sbrun** [dl1ksv/gr-funcube#7]
Hello,

 During a rebuild with gcc-12 on Debian, we notice that some tests failed

```
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python/qa_fcdpp.py", line 18, in <module>
    from funcube_python import fcdpp
ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"

5: Traceback (most recent call last):
5:   File "/<<PKGBUILDDIR>>/python/qa_fcd_control.py", line 12, in <module>
5:     from funcube_python import fcd_control
5: ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"
5: 
5: During handling of the above exception, another exception occurred:
5: 
5: Traceback (most recent call last):
5:   File "/<<PKGBUILDDIR>>/python/qa_fcd_control.py", line 18, in <module>
5:     from funcube_python import fcd_control
5: ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"
7: Traceback (most recent call last):
7:   File "/<<PKGBUILDDIR>>/python/qa_fcdpp_control.py", line 12, in <module>
7:     from funcube_python import fcdpp_control
7: ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"
7: 
7: During handling of the above exception, another exception occurred:
7: 
7: Traceback (most recent call last):
7:   File "/<<PKGBUILDDIR>>/python/qa_fcdpp_control.py", line 18, in <module>
7:     from funcube_python import fcdpp_control
7: ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"
7/8 Test #5: qa_fcd_control ...................***Failed    0.24 sec
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python/qa_fcd_control.py", line 12, in <module>
    from funcube_python import fcd_control
ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python/qa_fcd_control.py", line 18, in <module>
    from funcube_python import fcd_control
ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"

8/8 Test #7: qa_fcdpp_control .................***Failed    0.26 sec
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python/qa_fcdpp_control.py", line 12, in <module>
    from funcube_python import fcdpp_control
ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python/qa_fcdpp_control.py", line 18, in <module>
    from funcube_python import fcdpp_control
ImportError: generic_type: type "fcd_control" referenced unknown base type "gr::block"


50% tests passed, 4 tests failed out of 8

Total Test time (real) =   0.27 sec

The following tests FAILED:
	  5 - qa_fcd_control (Failed)
	  6 - qa_fcd (Failed)
	  7 - qa_fcdpp_control (Failed)
	  8 - qa_fcdpp (Failed)
Errors while running CTest
```
The build was made on version 1.0.0 but I also reproduce the issue with the latest version of gr-funcube.

Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012940

**Comment by dl1ksv** [comment]
You should use gnuradio with [patch](https://github.com/gnuradio/gnuradio/commit/307c0859b4b52e50cd4236a8ff2c10c3674e1dc0)

Otherwise GrPython.make will give wrong results under some circumstances.
And you should use either the latest gr-funcube or the maint-3.10 branch.
I tested on F36 with gcc-12 and it works fine.

**Comment by df7cb** [comment]
@dl1ksv, could you tag a new release with the fixes? Debian really likes to build packages from tarballs.

Thanks!

**Comment by dl1ksv** [comment]
@df7cb [Is v3.10.0.rc2](https://github.com/dl1ksv/gr-funcube/releases/tag/v3.10.0.rc2) ok?

**Comment by df7cb** [comment]
Perfect, thanks!

**Comment by ik8ozv** [comment]
Please anybody can help me to get it working under GQRX?
When i try to select the I/O Device, i can see two devices, one named
FUNCube Dongle V2.0 and another one named FUNCube Dongle V2.0 Stereo Analogico.
the first one has as Device string FCD=0
while the second one has as Device default_input=True,default_output=False,device_id=0,driver=audio,soapy=0.
If i select the first one the program closes down while if i choose the second one i bet the audio distorted and mixed with the background noise. It is not clear.
Please any help?
Thanks
Enzo
